### ISSUE TITLE
fuse layer creates backend pin twice

### ISSUE THREAD

**Issue by evgmik** [sahib/brig#100]
Steps to reproduce.
1. Mount `brig` via fuse
2. Copy any file to mount
Observe in logs:
```
fuse/util.go:18: errorize: dir-lookup: No such file: No such file or directory: /ztes2
20.02.2021/14:48:41 ⚙ catfs/mio/stream.go:138: guessed 'unknown' compression for file /ztes2
20.02.2021/14:48:41 ⚙ catfs/core/coreutils.go:470: adding /ztes2 (QmSG3yLbF6VfimqSiXoB8kSL8PkmC3w7X2zcaUsqFV2tKG)
20.02.2021/14:48:41 ⚙ fuse/file.go:37: fuse-file-attr: /ztes2
20.02.2021/14:48:41 ⚙ fuse/handle.go:75: fuse-Write: /ztes2 (off: 0 size: 4897)
20.02.2021/14:48:41 ⚙ fuse/file.go:119: fuse-file-setattr: request Setattr [ID=0x1a Node=0x4 Uid=1000 Gid=1000 Pid=24328] mtime=2021-02-20 14:48:41.545509997 -0500 EST handle=0x1
20.02.2021/14:48:41 ⚙ fuse/file.go:37: fuse-file-attr: /ztes2
20.02.2021/14:48:41 ⚐ fuse/handle.go:92: fuse: Write time 1.042131ms for 4897 bytes
20.02.2021/14:48:41 ⚙ fuse/handle.go:119: fuse-flush: /ztes2
20.02.2021/14:48:41 ⚙ catfs/mio/stream.go:138: guessed 'lz4' compression for file /ztes2
20.02.2021/14:48:41 ⚐ File exists; modifying. [file=/ztes2]
20.02.2021/14:48:41 ⚙ catfs/core/coreutils.go:470: adding /ztes2 (QmTshsWjvZG5x8ZLTsVSnVHYvbZwDP8Kuz6MBKJN9BdTou)
20.02.2021/14:48:41 ⚐ fuse/handle.go:129: fuse: Flashed `/ztes2` in 69.900689ms
20.02.2021/14:48:41 ⚙ fuse/handle.go:139: fuse-release: /ztes2
```

Note that `catfs/core/coreutils.go:470: adding /ztes2 (Qm...)` happens twice with different hash.

The first hash seems to always have size of 36 bytes.

**Comment by evgmik** [comment]
Turns out it is not a bug, it is how copy file works: 1st it create a file via `touch` which generates 1st backend pin, then it update the file content, which creates 2nd pin.

Would it make sense to have a special case for `touch` with zero content to always have the same encryption key (as we use to have when it was content generated)? This way touched files have the same backend pin, and we would save time on `ipfs` end, since it would not need to create already existing hash.
When there is a batch copy, it could save some time.

**Comment by sahib** [comment]
I'm not sure I understand what you mean by "same backend pin".

> Would it make sense to have a special case for touch with zero content to always have the same encryption key (as we use to have when it was content generated)?

How would you differentiate between cases where you actually just touch an empty file and cases where you touch and copy?
The 36 bytes above will be the size of the header, I guess.

**Comment by evgmik** [comment]
> I'm not sure I understand what you mean by "same backend pin".

`ipfs` creates some hash (backend pin for us) for the same content.

 
> > Would it make sense to have a special case for touch with zero content to always have the same encryption key (as we use to have when it was content generated)?
> 
> How would you differentiate between cases where you actually just touch an empty file and cases where you touch and copy?

This is easy, if we are at https://github.com/sahib/brig/blob/dcbd41a5c1c6857116337a6fc0e6a6995db86887/catfs/fs.go#L888
then we are touching a non existing file with zero content. So we can force the same encryption key. Which would result in the same backend hash (pin).

> The 36 bytes above will be the size of the header, I guess.

Yes, it is the header of an empty file.

**Comment by sahib** [comment]
> ipfs creates some hash (backend pin for us) for the same content.

Yes, that's the bit I did not understand. The content is not the same, right? One hash is added for the 36 bytes for the empty file and one for the full file with 4897 bytes. Or is it too late and I'm too tired?

> then we are touching a non existing file with zero content. So we can force the same encryption key. Which would result in the same backend hash (pin).

The logic is already that the key is generated when [a path is first touched](https://github.com/sahib/brig/blob/dcbd41a5c1c6857116337a6fc0e6a6995db86887/catfs/fs.go#L986). Note that if the compression hint is ``guess`` it might guess differently depending on the header's content.

**Comment by evgmik** [comment]
> > ipfs creates some hash (backend pin for us) for the same content.
> 
> Yes, that's the bit I did not understand. The content is not the same, right? One hash is added for the 36 bytes for the empty file and one for the full file with 4897 bytes. Or is it too late and I'm too tired?

I am arguing that the first touch should generate the same `ipfs` hash. After all the content is 0. It is not a problem with single file copy, but when we do a batch with a thousand files. We generate a thousand throw away "touched" `ipfs` hashes. But we can make them all to point to a single `ipfs` hash of an empty file.

> 
> > then we are touching a non existing file with zero content. So we can force the same encryption key. Which would result in the same backend hash (pin).
> 
> The logic is already that the key is generated when [a path is first touched](https://github.com/sahib/brig/blob/dcbd41a5c1c6857116337a6fc0e6a6995db86887/catfs/fs.go#L986). Note that if the compression hint is `guess` it might guess differently depending on the header's content.

When we are touching a new file, it randomly select an encryption key. Thus every touched ipfs hash is different.

But now I see the obstacle, the current logic keeps "assigned" encryption key, so we might end up with a thousand of files with the same encryption key. Which would be a security hole.

So I am guessing there is no one line fix, we would have to redo the logic.

**Comment by sahib** [comment]
> I am arguing that the first touch should generate the same ipfs hash.

Ah, now I got it. It's about multiple files, I had the context of the example in the first post.

> We generate a thousand throw away "touched" ipfs hashes. But we can make them all to point to a single ipfs hash of an empty file.

Yes, makes sense. Could be a small low-effort optimization.


> But now I see the obstacle, the current logic keeps "assigned" encryption key, so we might end up with a thousand of files with the same encryption key. Which would be a security hole. So I am guessing there is no one line fix, we would have to redo the logic.

Not really. ``preStageKeyGen()`` can have a special case (only reachable from ``Touch()``) where a size of 0 would return a static key (all zeros for example).  This key is then stored as part of the file node, until another Stage with the actual data occurs. This would notice that the file size and key is zero and would generate a proper one. In summary I'd expect this to be around 10 LOC. We should definitely add a test for this behavior though.

**Comment by evgmik** [comment]
ok. I will look into it.

**Comment by sahib** [comment]
Closing since it was handled by #103.
