### ISSUE TITLE
Install brig doesn't work as described

### ISSUE THREAD

**Issue by serztle** [sahib/brig#11]
### What did you do?

Install brig as described in `brig docs`.

### What did you expect to see?

Commands should work:

```
$ git clone --recursive https://github.com/sahib/brig
$ cd brig && make
$ sudo make install
```

### Workaround

```
$ go get -v -u github.com/sahib/brig
$ git clone --recursive https://github.com/sahib/brig
$ cd brig && make
$ sudo make install
```

### What did you see instead?

```
go build -ldflags \
	" \
		-X "github.com/sahib/brig/version".Major=0 \
		-X "github.com/sahib/brig/version".Minor=1 \
		-X "github.com/sahib/brig/version".Patch=0 \
		-X "github.com/sahib/brig/version".ReleaseType=alpha \
		-X "github.com/sahib/brig/version".BuildTime=`date -u '+%Y-%m-%dT%H:%M:%S%z'` \
		-X "github.com/sahib/brig/version".GitRev=`git rev-parse HEAD` \
	" \
	brig.go
brig.go:6:2: cannot find package "github.com/sahib/brig/cmd" in any of:
	/usr/lib/go/src/github.com/sahib/brig/cmd (from $GOROOT)
	/home/seb/.go/src/github.com/sahib/brig/cmd (from $GOPATH)
make: *** [Makefile:12: all] Error 1
```
### Did you check if a similar bug report was already opened?

Yes.

### System details:

go version:     ``go version go1.10.1 linux/amd64``
uname -s -v -m: ``Linux #1 SMP PREEMPT Thu Apr 12 17:46:07 UTC 2018 x86_64``

brig client version: ``v0.1.0-alpha+f924b10 [build: 2018-04-15T12:07:40+0000]``

**Comment by sahib** [comment]
This should be fixed as of 3a52db4c6ff7459a5e3c67c8e46390a032664a04 and daff2fa0d37c3abbe4532496f1b7baeebade9e99. I changed the install instructions to use a ``go get`` based strategy similar to [what ipfs does](https://github.com/ipfs/go-ipfs#build-from-source).
