### ISSUE TITLE
brig init: Unexpected "Password:" prompt

### ISSUE THREAD

**Issue by serztle** [sahib/brig#12]
### What did you do?

In home directory, daemon isn't running and BRIG_PATH isn't set:

```
$ brig init bob@wonderland
```

### What did you expect to see?

A error message: "Please set BRIG_PATH" or "There are files in the current directory, can't initialize!".

### What did you see instead?

```
$ brig init bob@wonderland
Password: 
```

### System details:

go version:     ``go version go1.10.1 linux/amd64``
uname -s -v -m: ``Linux #1 SMP PREEMPT Thu Apr 12 17:46:07 UTC 2018 x86_64``

brig client version: ``v0.1.0-alpha+f924b10 [build: 2018-04-15T12:07:40+0000]``

**Comment by sahib** [comment]
This password prompt here can be seen when there is an already existing repository and the daemon is not running. I think this is not a bug.
