### ISSUE TITLE
Installation error: unrecognized import path "math/bits"

### ISSUE THREAD

**Issue by flyingzumwalt** [sahib/brig#13]
I'm really excited to try out brig. Running only OSX right now. Is the code base still linux-only? 

When trying to install on OSX 10.13.4, I get this error:

> $ go get -d -v -u github.com/sahib/brig 
> github.com/sahib/brig (download)
> package math/bits: unrecognized import path "math/bits" (import path does not begin with hostname)

**Comment by lgierth** [comment]
I think you need to update golang -- math/bits was introduced only relatively recently.

**Comment by lgierth** [comment]
> brig only works with a newer version of Go (>= 1.9). The version in your package manager might be too outdated, if you’re on e.g. Debian. Make sure it’s up to date!

But best to just always go with the latest (1.10.1 at the moment)

**Comment by sahib** [comment]
Hello @flyingzumwalt,

@lgierth is right, you need at least go >= 1.9 (which introduced ``math/bits``).
Also yes, the code base is linux-only right now, but trying it out does not hurt I guess.
Be aware that the FUSE filesystem will not work out of the box.

**Comment by mitra42** [comment]
Just flagging that the dependency on go >= 1.9 will cause problems on Raspberry Pi's etc for which the `apt-get` version is still 1.7
