### ISSUE TITLE
Implement live updating

### ISSUE THREAD

**Issue by sahib** [sahib/brig#18]
It should be possible to trigger an update on remotes that allow it when we update a file.
Those peer will then receive the update without the need to invoke ``brig sync``.

This property should be part of the remote settings (similar to folders). Technically the ``pub/sub`` subsystem of IPFS might be a good candidate for this. Peers would subscribe to each other and publish a message with a set of change (i.e. a patch) with what changed. In case of changes this would result in a commit on both sides as a side effect.

**Comment by sahib** [comment]
> Implementing a sort of p2p-backed Dropbox styled mode would be very interesting.

That's the plan on the long term.

> Some peers synchronize shallowly, maybe with some cached data

What do you mean by *shallowly* in this case?

**Comment by sahib** [comment]
> I'm very glad to hear that!

Well, it will take a lot of work to get there. See also the [roadmap](https://brig.readthedocs.io/en/latest/roadmap.html) for some details.

> Shallowly not as in git --shallow, but rather as in presenting a libfuse filesystem to the user, and
> at access downloading the required data from all peers that have it.

What you call a "shallow copy"  is the default of brig. ``brig sync`` only transfers metadata. In every other aspect each brig instance acts as mere cache for data. The cache contents can be controlled by the pinning concept though. Later on, some remotes in your network (running on a big machine) would have a configurable policy that makes them keep max. 10 versions of a file for example, while other remotes are allowed to drop all files immediately after not having them used for a few minutes (think of smartphones or other thin clients).

**Comment by sahib** [comment]
I had some fun implementing live updating. It's indeed based on IPFS's PubSub system and works quite well (sometimes it still has connectivity issues though...). The changing side will simply send out a notification, which the receiving side sees. The receiving side starts a sync with the remote in question.
The amount of syncs per second is limited though, so you should not get a burst of syncs from all sides.

I wrote up some docuementation here: https://brig.readthedocs.io/en/develop/introduction.html#automatic-updating

**Comment by robertfoss** [comment]
Very cool! Are you able to receive updates from multiple peers at the same time?

**Comment by sahib** [comment]
> Very cool! Are you able to receive updates from multiple peers at the same time?

Yes. You'll receive updates for every remote you enabled auto-updating.

**Comment by robertfoss** [comment]
So I would be able to get the same (possibly large) update from multiple
peers at the same time too then?

**Comment by sahib** [comment]
> So I would be able to get the same (possibly large) update from multiple
peers at the same time too then?

Not sure if I understood the question right.

It depends what you understand by *same time* and *large*. ``brig`` is not a "real" network filesystem. It does not give you and posix-ish guarantees in what time updates may happen. If two remotes would change some file at the same time (and we allow receiving updates from them), the effect is the same as:

```bash
$ brig sync remote1
$ brig sync remote2
```

If we assume that both remotes changed the same file in a conflicting manner, we would get the version of ``remote1`` and a conflict file from ``remote2`` (assuming that we did not change the very same file).

The size of the update is not important, the notification itself does not contain any data related to *what* changed. Every remote that receives such a notification will check if they may sync with this remote automatically and execute something like ``brig sync some-remote`` internally or ignore the notification altogether. So, every update that works with ``brig sync`` will also work with the update mechanism.

**Comment by makeworld-the-better-one** [comment]
This is out of develop now, yes? Also, you could enable [gossipsub](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#gossipsub) for better routing, although it is experimental.

**Comment by sahib** [comment]
> This is out of develop now, yes?

Yes, it is. No official version yet, since the next version includes the gateway UI.

> Also, you could enable [gossipsub](https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md#gossipsub) for better routing, although it is experimental.

Good hint. Since all of ``brig`` is also quite experimental, this shouldn't matter too much.

**Comment by makeworld-the-better-one** [comment]
Glad I could help!

**Comment by sahib** [comment]
I will close this, since this feature is indeed implemented.
