### ISSUE TITLE
sudo make install does not copy the binary

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#21]
**Describe the bug**
Running `sudo make install` fails.

**To Reproduce**
Run that command. My output was:
```
'brig' binary does not exist; please run 'make build' before 'make install'
make: *** [Makefile:59: install] Error 1
```
Something is wrong with the line `ifneq ("$(wildcard brig)","")` in `Makefile` I'm assuming.

**Expected behavior**
It copies `~/go/bin/brig` to `/usr/local/bin`.

**Additional context**
I'm running Arch Linux, and Zsh.

Also, running `brig` works anyway, because per your instructions, I've added `~/go/bin` to my `PATH`. But `sudo make install` will install it for all users, which is important.

**Comment by sahib** [comment]
Hello @makeworld-the-better-one,

thanks for the report.

> Something is wrong with the line `ifneq ("$(wildcard brig)","")` in `Makefile` I'm assuming.

Yeah, I changed the ``build`` step to use ``go install`` instead of ``go build``. That's why the ``brig`` binary  did not exist in the local directory. It should work again as of 02d3b3bc444fb2fb59b7d714e112d480245c41c5.

The reason for not making ``build`` a dependency of ``install`` is: ``make install`` requires sudo privileges, but running ``go`` as root will break the compilation due to a different GOPATH. This is counter-intuitive, but I didn't find a good way to workaround this.

**Comment by makeworld-the-better-one** [comment]
@sahib thanks for the fix and quick reply. 

What if instead of copying the brig binary to the code directory (mixing code and binaries feels weird to me), you have `install` copy the binary from the the binary folder? For example, with the line `@sudo cp "$(GOBIN)/brig" /usr/local/bin`, and no copying line in `build`

**Comment by sahib** [comment]
> copy the binary from the the binary folder...

True, I wanted to do that first, but the location of the binary folder (``$GOBIN``) is different when invoked as root. This would require some trickery to get the right binary folder for the previous user. I hope to implement something like a [mage](https://github.com/magefile/mage) file, which would (maybe) make implementing this kind of trickery a bit easier and more robust.

**Comment by makeworld-the-better-one** [comment]
Ah yes of course. Well it works for now, but to avoid mixing code and binaries you could instruct the user to do that operation themselves, manually typing in their `$GOBIN` path for the `cp` operation. It's what I did anyway.

**Comment by sahib** [comment]
I removed the ``install`` step in the documentation for now (0b3322f0095ec6c2366630f71e5b373f06a9ca0a) until I found something better. It's not necessary anyway when you added ``$GOBIN`` to your ``PATH`` as described in the docs.

**Comment by makeworld-the-better-one** [comment]
I would also add the `cp` line for a global install, but it works for the user either way at least now. Thanks again, and for creating brig too!

**Comment by sahib** [comment]
Proper global install will come back some day.
