### ISSUE TITLE
Gateway feature requests/bugs

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#22]
A list of some gateway features I think will be nice. I'll add to this list as I think of them. I don't mean to overload you, so tell me if I should stop, but I want to put my thoughts somewhere. The gateway is awesome!

- Pinning / unpinning files
    - In the per-file menu and in the sidebar for when multiple files are selected
    - Maybe also some symbol beside the file showing whether it's pinned or not, like with `brig ls`
- Add the share button in the per-file menu
- The fingerprint in the remotes tab is cutoff, it's not as long as when you run `brig whoami`
- Being able to navigate and select folders when adding a remote instead of just having to enter folder names would be nice
    - Also it's unclear how to share everything - is it just putting a `/` in the folders section?

**Comment by sahib** [comment]
Thank you! I don't get a lot of feedback normally - appreciated.

> * Pinning / unpinning files [...]

Yes, it is still missing. I was debating with myself still on how to handle the pinning of older versions (which are currently neither easily viewable nor settable). The whole concepts needs a revamp which I want to do before investing much time in exposing the current pinning features. After all the gateway is a relatively direct visualization of the ``brig`` command line.

> * Add the share button in the per-file menu

Agreed.

> * The fingerprint in the remotes tab is cutoff, it's not as long as when you run `brig whoami`

Yes. I was trying to make it nicely visible without taking up too much space. Too bad ``brig`` cannot handle the shortened fingerprint... Guess I need to display it differently, for example as some "details" modal.

> * Being able to navigate and select folders when adding a remote instead of just having to enter folder names would be nice

Yes, I was lazy here. Side note: It is (in theory) possible to also name folders that do not exist. But there should be at least some sort of auto completion.

> * Also it's unclear how to share everything - is it just putting a / in the folders section?

Sharing everything is adding no folders at all. But adding ``/`` as folder will work too.

Also here: Pull requests are welcome. [Learning Elm is fun!](https://elm-lang.org/) :smirk:

**Comment by makeworld-the-better-one** [comment]
> Yes, it is still missing. I was debating with myself still on how to handle the pinning of older versions (which are currently neither easily viewable nor settable). The whole concepts needs a revamp which I want to do before investing much time in exposing the current pinning features. After all the gateway is a relatively direct visualization of the `brig` command line.

If I can offer my own opinion on pinning and versioning as a whole, I think when you pin a file without specifying a version/commit, brig should then always pin the newest version of the file, and unpin the old versions. But if someone manually pins a version of a file, then brig will keep pinning that version.

This could be done in the UI, where you have a pinning button beside the file, which just controls the updating newest version pin like I talked about. Then when you click the history button for the file, you can select and control the pinning of previous versions.

> Yes. I was trying to make it nicely visible without taking up too much space. Too bad `brig` cannot handle the shortened fingerprint... Guess I need to display it differently, for example as some "details" modal.

 Yeah, I would just display the full fingerprint, at least that way it can be used.

Thanks for replying to everything! Would you mind mentioning it here whenever you fix/add any of these I brought up? I will look into Elm, I don't really know Javascript but if you've already got some stuff then maybe I can hack around :laughing:

**Comment by sahib** [comment]
> If I can offer my own opinion on pinning and versioning as a whole, I think when you pin a file without specifying a version/commit, brig should then always pin the newest version of the file, and unpin the old versions. But if someone manually pins a version of a file, then brig will keep pinning that version.
> 
> This could be done in the UI, where you have a pinning button beside the file, which just controls the updating newest version pin like I talked about. Then when you click the history button for the file, you can select and control the pinning of previous versions. 

All good points and this is mostly how ``brig`` works already. But I also want to make it easy to do something like "keep the last 10 versions" and possibly even more fine grained constraints like "pin it, but not if it exceeds my storage". The plan here is that different instances of ``brig`` could be configured differently. A node on a server might store ~20 versions, while my laptop will just keep the newest one.

> Yeah, I would just display the full fingerprint, at least that way it can be used.

Done as of 1189cf6018861902032d5606c2e8e410a7953e97.

> Thanks for replying to everything! Would you mind mentioning it here whenever you fix/add any of these I brought up?

Would have done that anyways:

* As of b5eb59248f82334379e59e326a6133f7d11f161c , the "folders" dialog now works similar to the move/copy dialog. It shows a list of all folders to pick from.
* As of 27378c862ff373be7999e5d01dec9a82d7f61841 there is a "share" button per entry.

> I will look into Elm, I don't really know Javascript but if you've already got some stuff then maybe I can hack around. 

Depends what you like more. If you know Go, there's also enough work open on the backend side. :smirk: Learning Elm has a very steep learning curve if you did not have any prior exposure to frontend development. Just tell me what area you're interested in and I can give you hints on what needs to be worked on and how to learn what's required to do it. The frontend code lives [here by the way](https://github.com/sahib/brig/tree/master/gateway/elm/src).

**Comment by makeworld-the-better-one** [comment]
> All good points and this is mostly how `brig` works already. But I also want to make it easy to do something like "keep the last 10 versions" and possibly even more fine grained constraints like "pin it, but not if it exceeds my storage". The plan here is that different instances of `brig` could be configured differently. A node on a server might store ~20 versions, while my laptop will just keep the newest one.

Ohh, I see. That is more complicated, but I don't think it really needs to happen in the gateway, as that's an advanced feature. Just a simple pinning interface like brig already has would be great.

> Done as of [1189cf6](https://github.com/sahib/brig/commit/1189cf6018861902032d5606c2e8e410a7953e97).
As of [b5eb592](https://github.com/sahib/brig/commit/b5eb59248f82334379e59e326a6133f7d11f161c) , the "folders" dialog now works similar to the move/copy dialog. It shows a list of all folders to pick from.
As of [27378c8](https://github.com/sahib/brig/commit/27378c862ff373be7999e5d01dec9a82d7f61841) there is a "share" button per entry.

So many fixes, so soon! Thanks a lot!

> If you know Go

Unfortunately not. I plan to learn at some point.

> Learning Elm has a very steep learning curve if you did not have any prior exposure to frontend development. Just tell me what area you're interested in and I can give you hints on what needs to be worked on and how to learn what's required to do it.

That's me! Thanks for offering your help, I may take you up on that at some point.

**Comment by sahib** [comment]
As of 127cbd0c1f53fd98ee9fc6ba350218c4adb1ffa5 the pin state is also shown in the list view and the history modal. This still has some funny consequences for directories, but I'll work that out.

**Comment by sahib** [comment]
I guess all issues were worked on? Can I close this?

**Comment by makeworld-the-better-one** [comment]
Yep, thanks again!
