### ISSUE TITLE
Use already running IPFS daemon

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#23]
Pretty much the title text. It'd be nice to be able to have brig use an already install IPFS daemon, and the `.ipfs` folder for non-brig specific data, etc. This way those of us already using IPFS don't need to run two daemons at once or anything. Maybe brig can look for an already running daemon before it tries to start one?

**Comment by sahib** [comment]
That's harder than it sounds: Currently ``brig`` uses the internal API of IPFS to communicate with the node. Talking to an existing IPFS node would be done over [IPFS's HTTP API](https://docs.ipfs.io/reference/api/http/) - last time I checked there were a few issues:

* Not all methods were supported (docs look more complete now, so might have changed)
* The API was not marked stable yet (might have changed?)
* The ``cat`` operation needs to be seek-able. While this [seems possible](https://docs.ipfs.io/reference/api/http/#api-v0-cat) it would be less efficient than the current solution. Whenever someone seeks in the stream, it would have to close the current connection, make a new connection at the specified offset and output it from there.
* There was no decent http client library available.

On the plus side, debugging and profiling would be a lot easier without having IPFS in the same process.
Also, I wouldn't need to pack all of IPFS in the binary. It's doable, but the result might not be on-par with the current solution speed-wise and implementation might require some time.

Some reference:

* ``brig`` can support more backends, as long a backend can implement [this interface](https://github.com/sahib/brig/blob/master/backend/backend.go#L32) (which is an amalgamation of several other interfaces: [fs](https://github.com/sahib/brig/blob/master/catfs/backend.go#L25), [repo](https://github.com/sahib/brig/blob/master/repo/backend.go#L9), [net](https://github.com/sahib/brig/blob/master/net/backend/backend.go), [events](https://github.com/sahib/brig/blob/master/events/backend/backend.go))
* The new backend needs to implement all of the functions specified in those interfaces in a stable way.
* The current embedded implementation can be found [here](https://github.com/sahib/brig/tree/master/backend/ipfs).

Pull requests welcome. I might do it some day myself, but I have other priorities right now.

**Comment by makeworld-the-better-one** [comment]
Ah, I didn't realize it would be difficult, I forgot you weren't using the HTTP api. Using the HTTP api might be more versatile in the long run, as you can specify remote nodes and all those kinds of things, but I understand that it's probably easier within go.

**Comment by sahib** [comment]
> ...as you can specify remote nodes and all those kinds of things, but I understand that it's probably easier within go.

I hope 

> I found [this one](https://github.com/ipfs/go-ipfs-api/) from the IPFS devs. Have you seen it?

Yes, saw that one. That's the one I referred to actually. There were some limitations which I don't quit remember (beside what I listed above). But there were some commits in the mean time, so I might have another look.

> Could you use that?

With a bit of work, yes. Time is more of a problem here. :smile:

> And then the brig will look for an existing daemon, or be given something like `--daemon-port=XXXX`, and if it can't find one it'll start its own daemon, but still use the same library.

Yes, that would be an option that could be passed to ``init``. The default option would be what you described (use existing if started or ``~/.ipfs`` exists).

**Comment by makeworld-the-better-one** [comment]
Glad to hear it's possible and on your radar! Of course these things take time, but whenever you get to it, it would be helpful to me.

**Comment by sahib** [comment]
Implemented it in ``features/ipfs-http`` and merged that branch to ``develop`` today. It was less painful than I expected and helped a lot by cleaning up some older hacks that I had to do to use ``ipfs`` as a library. Also the new code should be easier to debug and profile since ``brig`` is idling most of the time now. The normal ``ipfs`` backend was removed for those cleanup reasons as well.

It is even possible now to have more than one ``brig`` repository per IPFS instance. I do not recommend that though, since pinning could interfere - but still useful for testing purpose. I will update the documentation in the next few days and do some more testing.

**Comment by makeworld-the-better-one** [comment]
Yay! Will brig just automatically detect the daemon, or do need to issue a command?

**Comment by sahib** [comment]
It will detect the daemon. If IPFS is not installed, it will install it. If IPFS is not running it will start a daemon. There is some detail work to be left (especially when running more than one daemon).

**Comment by makeworld-the-better-one** [comment]
```
❯ brig whoami
Password: 
02.03.2019/20:07:17 ⚡ cmd/parser.go:526: rpc: connection closed

~/go/src/github.com/sahib/brig develop
❯ brig net status
Password: 
02.03.2019/20:07:35 ⚡ cmd/parser.go:526: rpc: connection closed

~/go/src/github.com/sahib/brig develop
❯ brig status
Password: 
02.03.2019/20:08:18 ⚡ cmd/parser.go:526: rpc: connection closed

~/go/src/github.com/sahib/brig develop
❯ brig --repo ~/.brig status
Password: 
02.03.2019/20:10:40 ⚡ cmd/parser.go:526: rpc: connection closed
```

This is with brig from develop, without an IPFS daemon running. It looks like brig isn't starting it's own daemon, and I searched through the processes on my computer and confirmed that.

**Comment by sahib** [comment]
Did you do another ``init``? There were some changes that are incompatible with the previous status. Also executing with ``brig --verbose`` helps troubleshooting these kind of issues.  If that doesn't help, ``journalctl -ft brig`` will show you the daemon log.

**Comment by makeworld-the-better-one** [comment]
Running `init` without the daemon running doesn't work, it should start it's own daemon.
```
~/go/src/github.com/sahib/brig develop
❯ brig init makeworld@protonmail.com/laptop
-- Guessed folder for init: /home/makeworld/.brig
-- Guessed IPFS repository as /home/makeworld/.ipfs
03.03.2019/10:31:01 ⚡ cmd/parser.go:526: stat /home/makeworld/.ipfs/api: no such file or directory
```

Running `init` with `ipfs daemon` running works fine though, and creates the repo, etc.

**Comment by makeworld-the-better-one** [comment]
These are the ideal ways `brig` would act, correct? We can check them off as we test.

- [ ] `brig` starts its own daemon if the IPFS daemon isn't running when first starting
- [ ] `brig` automatically uses an already running IPFS daemon when first starting, if it exists
- [ ] `brig` will work with any IPFS daemon, even if the API is on a different port

Some additional ones, I don't know if these are as needed but it would be good I think.

- [ ] `brig` will switch to an IPFS daemon if its daemon is manually shutdown (`brig daemon quit`), and an IPFS daemon is running 
    - The key thing here is that it will use it's own daemon if it's already running. This allows people to choose which should be used.
- [ ] `brig` will switch to its own daemon if the IPFS one it's using stops running. Ideally this happens automatically so that the user never has to worry about it.

Is that all right, pretty much what you were thinking when you coded this? Or were you thinking it would act differently?

**Comment by sahib** [comment]
Note: Below is how I think it should work, although some bugs still might prevent that.

> ￼ brig starts its own daemon if the IPFS daemon isn't running when first starting

Yes. If it does not find a running daemon, it will try to start one from whatever ``IPFS_PATH`` is set to (if empty ``~/.ipfs``). 
> brig automatically uses an already running IPFS daemon when first starting, if it exists

Yes, ``brig`` reads the file ``$IPFS_PATH/api`` to see what port it needs to connect to. That's the step where it failed for you. I might need to have a fallback strategy for that (looks at the ``$IPFS_PATH/config`` e.g.)

> brig will work with any IPFS daemon, even if the API is on a different port

Yes, see above. Also you can choose what IPFS daemon to use if you run more than once with ``--ipfs-path`` on startup. You're also able to change it later via ``brig cfg set daemon.ipfs_port 5001``.

----

>  brig will switch to its own daemon if the IPFS one it's using stops running. Ideally this happens automatically so that the user never has to worry about it.

What for? If the original daemon is not available we would probably not be able to retrieve files from it.
Writing new files to a new daemon just adds to the confusion.

-----

Also, when I say "own daemon" I mean a forked off process since IPFS is not running in the same process as ``brig`` anymore.

**Comment by makeworld-the-better-one** [comment]
> Yes, brig reads the file $IPFS_PATH/api to see what port it needs to connect to. That's the step where it failed for you. I might need to have a fallback strategy for that (looks at the $IPFS_PATH/config e.g.)

What failed for me actually was that brig found that there wasn't an api file, and then didn't choose to start its own daemon instead. It just didn't do anything.

> What for? If the original daemon is not available we would probably not be able to retrieve files from it. Writing new files to a new daemon just adds to the confusion.

Ah yes of course, I forgot about that. That doesn't make sense, you're right.

**Comment by sahib** [comment]
> What failed for me actually was that brig found that there wasn't an api file, and then didn't choose to start its own daemon instead. It just didn't do anything.

Should be fixed as of e95ebed6. It just confused because the ``api`` file was not there and jumped over the next step.

**Comment by makeworld-the-better-one** [comment]
Ok, that's good. I'll test over the next few days.

**Comment by makeworld-the-better-one** [comment]
```
❯ brig init makeworld@protonmail.com/laptop
-- Guessed folder for init: /home/makeworld/.brig
-- Guessed IPFS repository as /home/makeworld/.ipfs
-- The API address of the repo is: /ip4/127.0.0.1/tcp/5001
-- IPFS Daemon does not seem to be running.
-- Will start one for you.
-- Waiting up to 60s for it to fully boot up...
-- Started IPFS as child of this process.
-- Will set some default settings for IPFS.
-- These are required for brig to work smoothly.
  -- Executing: IPFS_PATH='/home/makeworld/.ipfs' ipfs config --json Experimental.Libp2pStreamMounting true
could not set config: Error: api not running
command was: `ipfs config --json Experimental.Libp2pStreamMounting true
`  -- Executing: IPFS_PATH='/home/makeworld/.ipfs' ipfs config --json Experimental.QUIC true
could not set config: Error: api not running
command was: `ipfs config --json Experimental.QUIC true
`  -- Executing: IPFS_PATH='/home/makeworld/.ipfs' ipfs config --json Swarm.EnableRelayHop true
could not set config: Error: api not running
command was: `ipfs config --json Swarm.EnableRelayHop true
`  -- Executing: IPFS_PATH='/home/makeworld/.ipfs' ipfs config --json Reprovider.Interval "2h"
could not set config: Error: api not running
command was: `ipfs config --json Reprovider.Interval "2h"
`  -- Executing: IPFS_PATH='/home/makeworld/.ipfs' ipfs config --json Swarm.ConnMgr.LowWater 100
could not set config: Error: api not running
command was: `ipfs config --json Swarm.ConnMgr.LowWater 100
`  -- Executing: IPFS_PATH='/home/makeworld/.ipfs' ipfs config --json Swarm.ConnMgr.HighWater 200
  -- Executing: IPFS_PATH='/home/makeworld/.ipfs' ipfs config --json Swarm.ConnMgr.GracePeriod "60s"
✔  New passphrase: 
Well done! Please re-type your password now for safety:
✔  Retype passphrase: 
estimated time needed to crack password (according to zxcvbn): 3.0 months
Password: 

       _____         /  /\        ___          /  /\ 
      /  /::\       /  /::\      /  /\        /  /:/_
     /  /:/\:\     /  /:/\:\    /  /:/       /  /:/ /\ 
    /  /:/~/::\   /  /:/~/:/   /__/::\      /  /:/_/::\ 
   /__/:/ /:/\:| /__/:/ /:/___ \__\/\:\__  /__/:/__\/\:\
   \  \:\/:/~/:/ \  \:\/:::::/    \  \:\/\ \  \:\ /~~/:/
    \  \::/ /:/   \  \::/~~~~      \__\::/  \  \:\  /:/
     \  \:\/:/     \  \:\          /__/:/    \  \:\/:/
      \  \::/       \  \:\         \__\/      \  \::/
       \__\/         \__\/                     \__\/




     A new file README.md was automatically added.
     Use 'brig cat README.md' to view it & get started.



```

Are those errors normal? Also, is there a way that brig won't mess up my existing IPFS config, if it's using it's own daemon? I was thinking it should change its own daemon's config, but not mine. And then if I'm running my own daemon and it uses that instead of starting its own, it should respect my settings unless `brig` will break without them. For example, I don't want `brig` to change my `LowWater` and related settings, or to set `EnableRelayHop` to `true`.

**Comment by makeworld-the-better-one** [comment]
In addition, `brig` seemed to have started both it's own daemon, and a regular IPFS daemon on my computer for some reason, and the IPFS daemon did not stop when I ran `brig daemon quit`, only the `brig`  one did. There should only be one daemon, the `brig` one, I was thinking.

**Comment by sahib** [comment]
> Are those errors normal? 

No...

> Also, is there a way that brig won't mess up my existing IPFS config,

Two options are required (``Experimental.Libp2pStreamMounting`` and ``--enable-pubsub-experiment``).
Sadly, for some weird reasons, IPFS decided to make pub/sub not a config value, but an option passed to the daemon. While this will change in the future, this puts me in the unfortunate situation that I would have to potentially restart an existing daemon (which I don't yet). All other options area only for optimization purposes - I can add a flag that prevents setting those options, but I wouldn't make this the default use case since most users probably don't care a lot about how their IPFS is running. Still not 100% decided here though.

> I was thinking it should change its own daemon's config, but not mine.

With the latest changes there is no such concept as "*its own daemon*". It can use whatever daemon it finds (by default whatever ``IPFS_PATH`` points to, if set). You can always choose another IPFS daemon via ``brig init <user> --ipfs-path /tmp/your-new-ipfs-repo`` or set it later via ``brig cfg set daemon.ipfs_port 5002``.

> In addition, brig seemed to have started both it's own daemon, and a regular IPFS daemon on my computer for some reason

I guess it's a timeout issue then. ``init`` will start a new daemon, if none is running yet (as the log tells you) it will start one via ``IPFS_PATH=/home/makeworld/.ipfs ipfs daemon &``. While I have counter measures against that, it seems the daemon did not accept commands yet when we set the config values.

> [...] and the IPFS daemon did not stop when I ran brig daemon quit? 

Why would it? You can still use an already running IPFS daemon - which might be used for other purposes than ``brig``. 

> There should only be one daemon, the brig one, I was thinking.

No, it's always two processes now. No internal daemon anymore.

**Comment by sahib** [comment]
> I think that's the key to my errors. Can you wait for the API to be up (maybe by repeatedly trying to access it), and then try set those values, possibly with a timeout of 30 secs? You can see above that the later config commands worked, likely because the daemon had started by that point.

The current strategy was to wait until the port used by IPFS is open. As of ``develop`` I now check if I can issue a ``version`` command. Seems to be running smooth for me.

> That flag would be helpful. Alternatively, you could look at what the config was before, and restore it back to those setting when the brig daemon shuts down. I just feel weird about brig permanently modifying users' IPFS settings, especially things like Swarm.EnableRelayHop.

I added a flag to ``init``: ``--no-ipfs-optimization``.

**Comment by makeworld-the-better-one** [comment]
> As of `develop` I now check if I can issue a `version` command.

Ah good idea, that's what we do at @tomeshnet as well, you can see it [here](https://github.com/tomeshnet/prototype-cjdns-pi/blob/master/scripts/ipfs/ipfs-swarm.sh#L7).

> I added a flag to `init`

Thanks!

**Comment by makeworld-the-better-one** [comment]
I tested:
- `brig init` without a daemon running - IPFS daemon started
- `brig daemon quit` - IPFS daemon stayed
- Running `brig ls` with no brig daemon but an IPFS daemon - the IPFS daemon was not affected and a second one was not started - but the brig daemon started up again as expected
- Running `brig ls` with no daemons of any kind running - both the IPFS and brig daemons started as expected

This all seems good, I would feel fine about closing the issue.

**Comment by sahib** [comment]
:+1:
