### ISSUE TITLE
Matrix chat for project?

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#27]
Hello @sahib!

I was thinking it would be a nice idea to have a [Matrix](https://matrix.org) chat for this project. Matrix is a decentralized (federated) chatting protocol, similar to IRC but with more functionality such as images and logging. It can bridge to IRC if you prefer that, and many software projects such as IPFS and Libp2p are using it. I thought it could be used to discuss development of the project and talk with you, as well as annouce releases, without having to cloud the repo with issues or feature requests. What do you think?

**Comment by sahib** [comment]
Hello @makeworld-the-better-one,

I've created a ``#brig`` room on ``matrix.org``. I invited you (or at least an user with the same avatar and name).

**Comment by sahib** [comment]
Added to the README as of 45f7c246. Will also add it to the documentation a bit later.
