### ISSUE TITLE
cannot acquire lock

### ISSUE THREAD

**Issue by TroyWilson1** [sahib/brig#30]
Please answer these questions before submitting your issue.
Please include anything else you think is helpful. Thanks!

### What did you do?
brig tree

### What did you expect to see?
The files listed in brig

### What did you see instead?
cannot acquire lock: Lock FcntlFlock of /Users/troy/testing/brig.test/data/ipfs/repo.lock failed: resource temporarily unavailable

### Did you check if a similar bug report was already opened?
Yes 

### System details:
go version:     ``go version go1.12 darwin/amd64``
uname -s -v -m: ``Darwin Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64``

brig client version: ``v.. [build: ]``
brig server version: ``v..+``
ipfs version:        ``0.4.18+``

**Comment by sahib** [comment]
Hello @TroyWilson1,

thanks for the bug report (and also for being the first one using ``brig bug``!)

> cannot acquire lock: Lock FcntlFlock of /Users/troy/testing/brig.test/data/ipfs/repo.lock failed: resource temporarily unavailable

That is a known issue that I never managed to fully debug. If it happens it usually works after a few tries - as silly as it is. This code was removed in the ``develop`` branch completely though. If you have some time I would appreciate if you could switch to ``develop`` (``cd $GOPATH/github.com/sahib/brig && git checkout develop && make``).

**Comment by sahib** [comment]
Closing due to missing input & obsolete code that was removed anyways.
