### ISSUE TITLE
Make conflict strategies per folder

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#31]
**Is your feature request related to a problem? Please describe.**
As you said in #28: 
>> Is there a way to set the conflict resolution strategy depending on the folder?

> Could be another feature request. Can you come up with a good use case to convince me it is needed?

In my head I often compare `brig` to Google Drive, which I know is unfair, but I also think it might be a good standard to think about. For example, Alice might want to share a folder as read-only, and so her remote, Bob, will want to use the `embrace` conflict strategy. Maybe it's a folder of some of her work, essays, photography, whatever. It's Alice's content, and there's no reason for Bob to edit it. But Alice is still working on them, or adding stuff daily, and so Bob will want to use `embrace`. But Bob and Alice are also working together on a project at work, maybe some code, or documentation for something. For that, they will need to collaborate, and so that folder will use the default strategy, `marker`. The way `brig` works now, where conflict resolution can only happen per remote, will not work in this case.

**Describe the solution you'd like**
Already existing commands such as `brig remote conflict-strategy embrace bob` will still work, and will use that strategy for all of Bob's folders. But there could also be an optional folder part to that command, so you could say `brig remote conflict-strategy embrace bob /public`, and now `/public` uses `embrace`, while all of Bob's other folders just use whatever was in use before. This would also be in the gateway, so you could set the strategy per folder, as a part of that folder's dropdown or something.

**Describe alternatives you've considered**
For the situation I've described above, the best work around would be for Bob to leave the conflict strategy for Alice to `marker`, and then not touch any of the files in the folder she shared as read-only. This would work okay as long as Bob doesn't make a mistake and forget, but that might be asking too much of users :wink:

**Comment by sahib** [comment]
> But Bob and Alice are also working together on a project at work, maybe some code, or documentation for something. 

I should just note here that ``brig`` is not supposed to replace things like ``git``. If you plan to use ``brig`` mainly for collaboration, ``git`` might be the better option. You probably know that, I just wanted it to write down for other people reading this.

> [...]

Otherwise a sensible feature request that feels like an logical extension to the current state. This brings some corner cases up that need to be handled - i.e. files that were moved from a ``embrace`` folder to an ``ignore`` folder (possibly over an existing file).

**Comment by makeworld-the-better-one** [comment]
> If you plan to use `brig` mainly for collaboration, `git` might be the better option.

I was thinking that `brig` could be somewhat similar to Google Drive, where sharing and collaborating can happen. Git is good for code and many things, but not for the average person to share their documents.

Anyway, I'm glad you think the FR makes sense. Keep me updated!

**Comment by sahib** [comment]
> I was thinking that brig could be somewhat similar to Google Drive, where sharing and collaborating can happen. Git is good for code and many things, but not for the average person to share their documents.

Yeah, collaborating can happen, as long you don't need file diffs (okay, even then we might come up something, since there are enough diff tools available). That's why I said "*might*". I actually had code in mind, should have been more specific.

> Anyway, I'm glad you think the FR makes sense. Keep me updated!

I've implemented it in the latest develop. For reference, I used this script for testing:

```bash
alias ali='brig --repo /tmp/ali'
alias bob='brig --repo /tmp/bob'

echo "ali state" > ali-state
echo "bob state" > bob-state

ali stg ali-state embrace/x
ali stg ali-state ignore/x
ali stg ali-state marker/x
ali stg ali-state none/x

ali rmt f add bob /marker -c marker
ali rmt f add bob /ignore -c ignore
ali rmt f add bob /embrace -c embrace
ali rmt f add bob /none -r

bob sync > /dev/null

bob stg bob-state embrace/x
bob stg bob-state ignore/x
bob stg bob-state marker/x
bob stg bob-state none/x

ali sync bob
echo "###"
ali tree
echo "###"
ali cat embrace/x
ali cat ignore/x
```

(this assumes two running instances of ``brig`` as set up by the ``test-bed.sh`` script)


The output was:

```
Added:
  /bob-file

Ignored:
  /README.md.conflict.0
  /marker/x.conflict.0

Resolved Conflicts:
  ⇄ /embrace/x

###

•
├── ali-file ✔
├── bob-file
├── embrace/
│  └── x
├── ignore/ ✔
│  └── x ✔
├── marker/
│  ├── x ✔
│  └── x.conflict.0
├── none/ ✔
│  └── x ✔
├── README.md ✔
└── README.md.conflict.0 ✔

###

bob-state

###

ali-state
```

**Comment by makeworld-the-better-one** [comment]
> I've implemented it in the latest develop.

Thanks! I'll check it out. I assume it is also in the gateway UI? 

Also, can you add a remote, and then later change one of their folder's strategy? Such as adding Bob, and then running `brig remote folder add bob /collab -c embrace`?

**Comment by sahib** [comment]
> I assume it is also in the gateway UI?

Yes, it is.

![ui](https://i.imgur.com/od6I1DT.png)

> Also, can you add a remote, and then later change one of their folder's strategy?

Sure, there's no ``set`` command yet, but you can simply remove a folder and add it again. The folders are read anew on every sync.

**Comment by sahib** [comment]
> Sure, there's no set command yet, but you can simply remove a folder and add it again. [...]

As of b8f311b3 you can now overwrite the folders directly to make this a little less awkward:

```bash
$ brig remote folder set bob /public /collab -c embrace 
# or short:
$ brig r f s bob /public /collab -c embrace 
```

**Comment by makeworld-the-better-one** [comment]
Thanks! Could you add documentation for that and merge it into `develop` next time you have the opportunity?

**Comment by sahib** [comment]
Mentioned as of d26e6503.

**Comment by sahib** [comment]
Closing since the original feature request was implemented.
