### ISSUE TITLE
Allow for remote IPFS APIs

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#32]
**Is your feature request related to a problem? Please describe.**
Since `brig` is now using the HTTP IPFS API, one should be able to connect to any IPFS daemon, not just the local one. This was asked about by @postables in the chatroom. 

**Describe the solution you'd like**
Instead of using the `--ipfs-path` flag, there should be an `--ipfs-api` flag and an `--ipfs-port` flag. The former will allow for specifying an address to a node such as `11.22.33.44/example`, or `example.com`. The latter option can specify a port to use, and would default to `5001`, the IPFS default. If `--ipfs-api` isn't specified `127.0.0.1` can be used.

**Describe alternatives you've considered**
You could connect a remote port to your local device using `ssh` as a hack for the time being.

**Comment by sahib** [comment]
> Since brig is now using the HTTP IPFS API, one should be able to connect to any IPFS daemon, not just the local one. This was asked about by @postables in the chatroom.

I wonder what the added value/use case is here. Running ``brig`` not on the same machine as the IPFS daemon seems rather slow to me. Also the IPFS default is not to allow connections from the outside to the API. Maybe @postables can help here. If you can give me a valid use case this could be a feature.

**Comment by MafiaInc** [comment]
I have a IPFS running as docker container on the same host as brig, however direct ipfs command is not available so I got this:
``` shell
$ brig init --no-ipfs-setup --ipfs-path /mnt/ipfs_data/storage/ user@example.net/nas
-- Guessed folder for init: /home/user/.brig
-- IPFS repository is supposed to be at /mnt/ipfs_data/storage/
-- The API address of the repo is: /ip4/0.0.0.0/tcp/5001
-- IPFS Daemon seems to be running. Let's go!
-- Will set some default settings for IPFS.
-- These are required for brig to work smoothly.
-- The IPFS version is »0.6.0«.
  -- Setting config: IPFS_PATH='/mnt/ipfs_data/storage/' ipfs config --json Experimental.Libp2pStreamMounting true
could not set config:
command was: `ipfs config --json Experimental.Libp2pStreamMounting true
`  -- Setting config: IPFS_PATH='/mnt/ipfs_data/storage/' ipfs config --json Experimental.QUIC true
could not set config:
command was: `ipfs config --json Experimental.QUIC true
`  -- Setting config: IPFS_PATH='/mnt/ipfs_data/storage/' ipfs config --json Reprovider.Interval "1h"
could not set config:
command was: `ipfs config --json Reprovider.Interval "1h"
`  -- Setting config: IPFS_PATH='/mnt/ipfs_data/storage/' ipfs config --json Swarm.ConnMgr.GracePeriod "60s"
could not set config:
command was: `ipfs config --json Swarm.ConnMgr.GracePeriod "60s"
`  -- Setting config: IPFS_PATH='/mnt/ipfs_data/storage/' ipfs config --json Swarm.EnableAutoRelay true
could not set config:
command was: `ipfs config --json Swarm.EnableAutoRelay true
✔  New passphrase:
Well done! Please re-type your password now for safety:
✔  Retype passphrase:
estimated time needed to crack password (according to zxcvbn): centuries
Password:
09.07.2020/00:44:33 ⚡ src/brig-0.4.1/cmd/parser.go:543: rpc: connection closed
✔ ~

```
Anyway, after manually configuring these values in IPFS config I managed to make brig init the repo and it seems is running fine. I will do some more testing in the following days. By the way QUIC is enabled by default in newest version and it's not experimental anymore.

**Comment by sahib** [comment]
Done as of #99.
