### ISSUE TITLE
Name not showing up properly in Gateway

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#33]
**Describe the bug**
Under the remotes tab of the gateway, the Name of the repo creator doesn't show up properly.

![image](https://user-images.githubusercontent.com/25111343/54653074-b0e3ab00-4a8f-11e9-93fd-a559047e1860.png)

**Expected behavior**
It should display something like `myname@example.com/device`.

**Comment by makeworld-the-better-one** [comment]
The fingerprint also doesn't show up properly, it shows up on two lines instead of one. This makes copying difficult.

**Comment by sahib** [comment]
Confirmed. The wrong field was exported to the frontend. Should be fixed as of 88087ff0.

> The fingerprint also doesn't show up properly, it shows up on two lines instead of one. This makes copying difficult.

Showing it in one line makes displaying difficult, so I picked the lesser of two evils.

**Comment by makeworld-the-better-one** [comment]
Thank you. 

I still think it makes sense to display it properly, otherwise it makes copying difficult. Maybe you could just have a button that copies it to the clipboard instead of display the whole thing?

**Comment by sahib** [comment]
> Maybe you could just have a button that copies it to the clipboard instead of display the whole thing?

Good idea.

**Comment by makeworld-the-better-one** [comment]
Alternatively, there could also be a "View" or "View Fingerprint" button that brings up a modal with copyable text, a copy button, and potentially a QR code in the future. But the Copy button works as well, just another idea.

**Comment by makeworld-the-better-one** [comment]
Commit history indicates this was fixed as of ac357c721f41c747b502d9e1107e2a39d2c17b9e. Will test.

**Comment by makeworld-the-better-one** [comment]
Confirmed both name and copying the fingerprint work now. Thanks!
