### ISSUE TITLE
Can't enable auto update in gateway

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#36]
**Describe the bug**
Clicking the auto update slider to enable it did not work in the gateway. It did not slide over. 

**To Reproduce**
Add a remote. Try to enable auto update through the gateway

**Expected behavior**
It enables

**Additional context**
Enabling it works fine through the command line, and then it shows as enabled in the gatway.

---
I'd also like to add that setting auto enabling to true when adding the remote doesn't actually work, I have to try and enable it after adding as described above.

**Comment by sahib** [comment]
Confirmed. Actually tested this, but broke something else in the mean time it seems.

**Comment by sahib** [comment]
Should be fixed as of 594442ae.
