### ISSUE TITLE
brig diff is incorrect in gateway only

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#37]
**Describe the bug**
Looking at the diff with a remote in the gateway shows files that the remote doesn't have, but the files aren't shared with them either, show they should not show up. Strangely, `brig diff <remote>` does not show this file at all.

**To Reproduce**

1. Add a remote that has access to all folders
2. Allow them to sync
3. Change their access to only one folder
4. Allow sync
5. Click on their diff in the Remotes tab, and observe the files listed - the original shared files will be different
6. Check the output of `brig diff <remote>` as well, and observe how it doesn't match

**Please always include the output of the following commands in your report!**
I'm on the latest develop at the time of writing.
```
go version:     ``go version go1.12.1 linux/amd64``
uname -s -v -m: ``Linux #1 SMP PREEMPT Thu Mar 14 18:47:49 UTC 2019 x86_64``

brig client version: ``v0.4.1-beta+6fbc3c0 [build: 2019-03-22T21:14:30+0000]``
brig server version: ``v0.4.1-beta+6fbc3c0+6fbc3c0a48a6fe03e32deb193c5b49176df95f1c``
ipfs version:        ``0.4.18+``
```

**Additional context**
The remote originally had access to all folders of my device, which I think is why this file it no longer has access to is still showing up in the diff. My confusion is more why `brig diff` doesn't have the same issue.

**Comment by sahib** [comment]
I think this is part inconsistency on my side and part misunderstanding on your side.

To the inconsistencies first: ``brig diff <remote-name>`` will show you a diff between the most recent commits (``curr``) of both remotes, but will omit missing files by default (except ``-m`` is passed). The gateway diff compared the ``head`` commit, which is the commit before ``curr``, i.e. it does not include uncommitted changes. Also, it shows missing files. I changed this in af59d647.

> Allow them to sync
> Change their access to only one folder

Do you mean sync on both sides? And did you add the folder on both sides?

> The remote originally had access to all folders of my device, which I think is why this file it no longer has access to is still showing up in the diff. My confusion is more why brig diff doesn't have the same issue.
 
This is hard to reenact without knowing what folder and what file you're speaking of. When you add a folder for a remote, it just means that this remote will only be able to see the folders we specified on operations like sync & diff. This also means that files that were synced before are still visible to the remote (in the versions at this time). If the remote did not setup similar restrictions for us we're still able to see a full diff on his side, so adding a folder on our side does/should not influence the diff output for a remote.

For the ``brig diff`` issue: As explained above, the diffs had different defaults. which should be fixed now.

**Comment by makeworld-the-better-one** [comment]
Sorry for the poor explanation. I will test and see if that commit fixes it, I think it will.
