### ISSUE TITLE
"Download All" in gateway should use ZIP files

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#38]
**Is your feature request related to a problem? Please describe.**
While brig is only designed for UNIX systems, I believe part of the point of the gateway is that it can be accessed on many machines. Some of those will be Windows of course :cry:, and so the "Download All" feature that downloads a `.tar` archive will not be able to be opened by them.

**Describe the solution you'd like**
I think that instead of the "Download All" button downloading a `.tar` file, a `.zip` would be better, as it is better supported across all devices, such as Windows. This could also be supported in the CLI, maybe there could be an option that allows the user to choose between the two, and in the gateway it will just be the ZIP.

**Describe alternatives you've considered**
Any Windows user with 7zip will be able to open it, and while 7zip is popular, not everyone will have it, probably most Windows users won't. Extracting ZIP files is built into Windows, however.

**Additional context**
This would also happen for the "Download Selected" button.

**Comment by sahib** [comment]
> While brig is only designed for UNIX systems...

It's actually not. :smile: I just happen to use Linux. Pretty much else should be portable (except FUSE maybe) without too much hassle. But you're right in the sense that we probably do not attract many windows users currently.

> [...] will not be able to be opened by them.

Well, not without third party programs. But many popular programs like WinZip can indeed open ``.tar`` archives, so the situation is not that awful. You could still also download individual files as a last resort.

There are other technical issues why I choose ``.tar`` over ``.zip``. ``.zip`` has many options you can set from different compression levels, over encryption to extra fields. If I'd implement that, someone would come and ask for this until I'd have to implement a fully compliant archiving program - which is something I'd like to avoid (and I say that out of experience with ``rmlint``). Also ``.zip`` has its directory structure at the end, which doesn't make it very nice for streaming purposes. ``.tar`` in contrast is insanely simple and can be piped to whatever compression program you want.

Apart from that, I'm not opposed to having ``.zip`` as an option (with some standard settings). It's just something very low priority to me. Actually it would be a good first task for somebody to familiarize with the code base and I'd be happy to merge that in the end.

**Comment by makeworld-the-better-one** [comment]
Alright, I understand that it's low priority. Thanks for responding!
