### ISSUE TITLE
`master theses` in readme not found, is there another link about it?

### ISSUE THREAD

**Issue by GainSury** [sahib/brig#4]

**Comment by sahib** [comment]
The link got broken during the move from ``github.com/disorganizer/brig`` to ``github.com/sahib/brig``.
I fixed the README, direct links are here:

* https://disorganizer.github.io/brig-thesis/brig/thesis.pdf 
* https://github.com/disorganizer/brig-thesis/raw/master/security/pdf/thesis-final.pdf

Sadly, the papers are in german.
