### ISSUE TITLE
`brig remote ls` fails with offline remotes

### ISSUE THREAD

**Issue by makeworld-the-better-one** [sahib/brig#41]
**Describe the bug**
```
pi@tomesh-2c52:~ $ brig remote ls
28.03.2019/20:47:51 ⚡ cmd/parser.go:543:  dial: by-addr: auth: read tcp 127.0.0.1:40704->127.0.0.1:42151: read: connection reset by peer
pi@tomesh-2c52:~ $ brig ls
SIZE    MODTIME                       PATH         PIN  
630 kB  Wed Mar 20 02:07:11 UTC 2019  /share-test   ✔   
```
This machine is authenticated with a remote that isn't online, and actually doesn't exist anymore. Brig is running fine, but that specific command fails.

**To Reproduce**

1. Connect two machines
2. Turn off brig on one of them
3. Run `brig remote ls` on the online one and see the error

**Please always include the output of the following commands in your report!**
The machine above is running from the 0.4.0 ARM binary, on Raspbian - it's a Raspberry Pi 3.

uname -s -v -m: ``Linux #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l``

brig client version: ``v0.4.0+b3de1f1 [build: 2019-03-19T15:36:09+0000]``
brig server version: ``v0.4.0+b3de1f1+b3de1f119735e0f3fb5e5f9bccc7893418c098d4``
ipfs version:        ``0.4.18+``

**Expected behavior**
The remotes should be listed, even if they are offline.

**Additional context**
Running `brig remote edit` shows the remote I expect, so I know that in the backend the remote is known and everything.

**Comment by sahib** [comment]
That issue should be fixed in the ``develop`` branch already.
