### ISSUE TITLE
research: adding brotli and/or zstd compression algorithms

### ISSUE THREAD

**Issue by sahib** [sahib/brig#47]
Investigate in adding ``brotli`` and/or ``zstd`` as compression algorithms and figure out which mime types should use them.

**Comment by evgmik** [comment]
If we believe  [2017 study](https://gregoryszorc.com/blog/2017/03/07/better-compression-with-zstandard/) then we should focus on `zstd`. It seems to run faster for the same compression level.

But we probably should rework current heuristic for the compressor which is `mime` and file type based.
We could chose 1st block of the stream (64kB which is used for chunking) and try different compressors on it
and choose the best one based on compression/speed metric.

**Comment by sahib** [comment]
Good link, thanks. We can focus on ``zstd`` but adding both so users can choose is cheap too. It's only a matter of a few lines.

> We could chose 1st block of the stream (64kB which is used for chunking) and try different compressors on it
and choose the best one based on compression/speed metric.

Not sure if this is a good heuristic:

* Makes only sense for bigger files, due to the computation overhead incurred for small files. Only partial solution therefore.
* New hints system give user the option to change the default if he does not like the setting. Some users also favor speed over compression (or other way round) depending on their use case. So the compression/speed metric is not generally applicable.
* Makes implementation a bit more complex.

**Comment by sahib** [comment]
``zstd`` is now implemented, but did not live up to the hype compared to the improved ``lz4``. Maybe more benchmarks and/or improved implementations might improve that in the future. In the process though the streaming system was improved, so adding ``zstd`` was definitely a plus. Currently we do not select it using the ``guess`` hint.

``brotli`` was not tried, the [relevant go package](https://pkg.go.dev/github.com/andybalholm/brotli) seems to only support streaming APIs, for our use case a block based API would work better. Streaming might work too, but involves more copying and potentially more overhead due to headers.
