### ISSUE TITLE
Do not use MaxUint64 as indicator of unknow file size.

### ISSUE THREAD

**Issue by evgmik** [sahib/brig#53]
This is technically not a bug but make trigger some if a user
would use output of 
[CachedSize](
https://github.com/sahib/brig/blob/76c3335e7bec4c8643dcbc0ff061fda906ccb960/backend/httpipfs/pin.go#L237
) in something like `make([]byte, size)`.

What should be done:
Size should use int64 instead uint64, negative values should reinforce *unknown size* error/warning.

**Comment by evgmik** [comment]
I need some guidance here. We are using uint64 for the size allocation in multiple definitions through the code. Some examples
- https://github.com/sahib/brig/blob/75286a246ebc18037285e464824f7d5d9e2eea6e/catfs/repin.go#L16
- https://github.com/sahib/brig/blob/75286a246ebc18037285e464824f7d5d9e2eea6e/catfs/mio/stream.go#L92

So the original `brig` design was working with uint64.

Consequently, I am reluctant to change fuse logic to int64, which would avoid use of MaxUint64 as indicator of unknown size. As a reminder, we do send proper error in such occasion,  all occasion when MaxUint64 is used. 
The only exception is at https://github.com/sahib/brig/blob/75286a246ebc18037285e464824f7d5d9e2eea6e/catfs/backend.go#L127

So the main question: do we want to switch globally to int64?

**Comment by sahib** [comment]
> I need some guidance here. We are using uint64 for the size allocation in multiple definitions through the code. Some examples
> 
> * https://github.com/sahib/brig/blob/75286a246ebc18037285e464824f7d5d9e2eea6e/catfs/repin.go#L16
> * https://github.com/sahib/brig/blob/75286a246ebc18037285e464824f7d5d9e2eea6e/catfs/mio/stream.go#L92
> 
> So the original `brig` design was working with uint64.

``uint64`` is fine when you don't have a chance of invalid values - if I remember correctly that's the case for the two links above. If we have a state that should say *this value is invalid* and we can't use 0 for this, then we should change to a ``int64``.

> So the main question: do we want to switch globally to int64?

Yes. You can change the cases where you use ``MaxUint64`` to ``< 0`` and when FUSE needs a ``uint64`` you can safely cast it. But internally we should work with a ``int64``.
