### ISSUE TITLE
Proposal to show uncached files as simlinks with fuse

### ISSUE THREAD

**Issue by evgmik** [sahib/brig#65]
When we do fuse mount with `-o` (offline) option.
1. Let's assign file mode as symlink to uncashed files.
This way when someone asks for a listing, there will be nice visual (red font with colored list command) to remind that this file is uncached.

2. We might even show a link to the missing ipfs hash.

Item 2 is some extra work, but item 1 is easy. I already have a draft for it.

@sahib what do you think?

**Comment by sahib** [comment]
Yes, this sounds good to me. :+1:
