### ISSUE TITLE
Implement live benchmark command

### ISSUE THREAD

**Issue by evgmik** [sahib/brig#83]
Implement "live" benchmarks with something like `brig debug iobench`.
The idea was born in discussion of #82 

The idea is to test througput for
- for things like `brig cat` and `brig stage`
- fuse layer
- isolated benchmarks like encryption or compression

We could also output various system information that influences the benchmark results (CPU model, IPFS version etc.). All throughput numbers can also be expressed additionally as relative to the baseline (e.g. just copying bytes from ten-source to ten-sink).

**Comment by sahib** [comment]
Closing since it was covered extensively.
